routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\User;
use App\Team;


Auth::routes();

Route::get('/', function () {
    return redirect()->route('crm.dashboard');
});

Route::prefix('crm')->name('crm.')->middleware(['auth'])->group(function () {
    /**
     * User-facing screens
     */
    Route::get('/', 'CRMController@dashboard')->name('dashboard'); // Base CRM route
    Route::get('table/{list}', 'CRMController@listObjects')->name('list');
    Route::get('edit/{class}/{id?}', 'CRMController@editObject')->name('edit');
    Route::get('create/new/{class}', 'CRMController@createObject')->name('create');
    Route::get('history/{class}/{id}', "CRMController@history")->name('history');

    /**
     * Datatables
     */
    Route::get('data/{list}/{parent_id?}', 'DataController@getData')->name('dataTableData');
    Route::post('editor-update/interest', 'DataController@processInterestUpdate')->name('update-interest');
    Route::post('editor-update/{list}', 'DataController@processEditorUpdate')->name('update');
    Route::post('increase-discounts/{lead_id}', 'DataController@increaseDiscounts')->name('increase-discounts');

    /**
     * Form posts
     */
    Route::post('update/team/{team_id?}', 'FormController@updateTeam')->name('update-team');

    Route::post('update/lead/{id}', 'FormController@updateLead')->name('update-lead');
    Route::post('update/lead/{id}/status', 'FormController@updateStatus')->name('update-status');
    Route::post('update/lead/{id}/owner', 'FormController@updateOwner')->name('update-owner');
    Route::post('update/lead/{id}/callback', 'FormController@updateCallback')->name('update-callback');
    Route::post('update/call', 'FormController@updateCall')->name('update-call');

    Route::post('update/lead/{id}/note/add', 'FormController@addNote')->name('add-note');
    Route::post('update/lead/{id}/sms/add', 'SMSController@sendSMS')->name('send-sms');

    Route::get('update/lead/{id}/delete-callback/{callbackId}', 'FormController@deleteCallback')->name('delete-callback');

    Route::post('create/user', 'FormController@createUser')->name('create-user');
    Route::post('update/user/{id}', 'FormController@editUser')->name('update-user');
    Route::post('update/user_image/{id}', 'FormController@editUserImage')->name('update-image');

    Route::post('member-survey', 'FormController@processMemberSurvey')->name('member-survey');

    Route::get('get-blocking-modal/{lead_id?}', 'CRMController@getBlockingModal')->name('get-blocking-modal');

    /**
     * Front-end scripts for returning content blocks to Ajax
     */
    Route::any('ajax/block/{block}/{id?}', 'CRMController@renderAjaxBlock')->name('ajax-block');

    // Impersonate routes ::
    Route::get('impersonate/start/{who}', function ($who) {
        $im = app('impersonate');
        $iam = $im->findUserById(\Illuminate\Support\Facades\Auth::user()->id);
        $whoiwanttobe = $im->findUserById($who);
        $im->take($iam, $whoiwanttobe);
        return redirect('/crm');
    });
    Route::get('impersonate/stop', function () {
        $im = app('impersonate');
        $im->leave();
        return redirect('/crm');
    })->name('stop-impersonation');

    /**
     * Manage Catalogue Items
     */

    Route::get('catalogue/view/{action}/{id?}','CatalogueItemController@views')->name('catalogue-items');
    Route::post('catalogue/update/{id}','CatalogueItemController@update')->name('update-catalogue-item');
    Route::post('catalogue/create','CatalogueItemController@create')->name('create-catalogue-item');
    Route::get('catalogue/delete/{id}','CatalogueItemController@delete')->name('delete-catalogue-item');
    Route::get('catalogue/reactivate/{id}','CatalogueItemController@reactivate')->name('reactivate-catalogue-item');
});

//Payment Routes
Route::prefix('payment')->name('payment.')->middleware(['auth'])->group(function () {

    Route::get('build/{id}','PaymentController@orderBuilder')->name('build');
    Route::post('full/process/{id}','PaymentController@processPayment')->name('full-payment');
    Route::post('partial/process/{id}','PaymentController@processPartPayment')->name('partial-payment');
    Route::get('defer/process/{id}','PaymentController@defferPayment')->name('defer-payment');
    Route::post('process/subscription','PaymentController@processSubscriptionPayment');
    Route::get('view/outstanding','PaymentController@viewOutstanding');
    Route::post('update/outstanding','PaymentController@outstandingPaymentUpdate')->name('additional-payment');

});
// SMS routes
Route::prefix('sms')->name('sms.')->middleware(['auth'])->group(function () {

    Route::get('balance','SMSController@readBalance');
    Route::get('send','SMSController@sendMessage');


});
// Reporting
Route::prefix('report')->name('report.')->middleware(['auth'])->group(function () {
    Route::get('/all', 'ReportingController@reportList')->name('exportable');
    Route::get('leadStatus/{startPoint}/{endPoint}', 'ReportingController@leadStatusRequest');
    Route::get('leadCallStats/{startPoint}/{endPoint}', 'ReportingController@leadCallsRequest');
    Route::get('leadCallbacks', 'ReportingController@leadCallsBacksRequest');
    Route::get('leadSources/{length?}', 'ReportingController@leadSourceRequest');
    Route::get('userSales/{id}','ReportingController@userSalesRequest');
    Route::get('teamSales/{teamID}','ReportingController@teamSalesRequest');

});


// Test Routes
Route::prefix('test')->name('test.')->group(function () {

    Route::get('allocation','APIController@leadDistribution');

    Route::get('curl','ExternalController@makePerson');

    Route::get('sms',"SMSController@readMessages");
    Route::get('sms-verify/{recipient}',"SMSController@verifyNumber");

    Route::get('sales',"PaymentController@updateInterestsPartial");

    Route::get('regex-test',function (){
        $lead = \App\Lead::find(54);
        echo "Is mobile ? ". $lead->isUkMobile();
    });

    Route::get('engagement/{leadID}','ExternalController@getEngagementHistory');


});

// Base Home route
Route::get('/home', 'HomeController@index')->name('home');

// entry point for
Route::post('/external/sms/inbound', 'SMSController@readMessage');

resources/views/crm/themes/basic/screens/catalogueItems.blade.php
@extends('crm.themes.'.config('crm.theme').'.layouts.app')

@section('content')


    <div class="container">

        <div class="row">

            <div class="card">
                @if (session()->has('success'))
                    <div class="alert alert-success">{{ session('success') }}</div>
                @endif
                <div class="card-header bg-dark text-light">
                    <h3>Catalogue Items</h3>
                </div>

                <div class="card-body">
                    <div class="card-title">
                        <a class="btn btn-outline-dark "  href="/crm/catalogue/view/new">New Catalogue Item <i
                                    class="fas fa-plus-square"></i></a>
                    </div>
                    <div class="col-sm-12">
                        <table class="table table-striped table-hover table-bordered">
                            <thead class="bg-warning bg-dark text-light">
                            <tr>
                                <th>Catalogue Item ID</th>
                                <th>Catalogue Item Title</th>
                                <th>Catalogue Item RRP</th>
                                <th>Catalogue Item Created On</th>
                                <th>Catalogue Item Deleted On</th>
                                <th>Catalogue Item Maximum Discount</th>
                                <th>Edit</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($catalogueItems as $catalogueItem)
                                <tr @if(!is_null($catalogueItem->deleted_at)) class="bg-danger text-light" @endif >
                                    <td>{{$catalogueItem->id}}</td>
                                    <td>{{$catalogueItem->title}}</td>
                                    <td>£{{number_format($catalogueItem->price,2)}}</td>
                                    <td>{{$catalogueItem->created_at}}</td>
                                    <td>@if(is_null($catalogueItem->deleted_at))
                                            N/A @else {{$catalogueItem->deleted_at}}@endif</td>
                                    <td>{{$catalogueItem->max_discount}}% - (£{{number_format($catalogueItem->price - (($catalogueItem->price / 100) * $catalogueItem->max_discount),2) }})</td>
                                    <td>
                                        <div class="btn-group">
                                            @if(!is_null($catalogueItem->deleted_at))
                                                <a class="btn btn-light btn-block"  href="/crm/catalogue/reactivate/{{$catalogueItem->id}}">Re-enable</a>
                                            @else
                                                <a class="btn btn-outline-warning btn-sm"  href="/crm/catalogue/view/edit/{{$catalogueItem->id}}">Edit Item</a>
                                                <a class="btn btn-outline-danger btn-sm"  href="/crm/catalogue/delete/{{$catalogueItem->id}}">Delete Item</a>
                                            @endif

                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>


        </div>

    </div>


@endsection

resources/views/crm/themes/basic/screens/dashboard.blade.php
@extends('crm.themes.'.config('crm.theme').'.layouts.app')

@section('content')
<main role="main" class="container">


        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
            @elseif(session()->has('unauth'))
            <div class="alert alert-danger">
                {{ session()->get('unauth') }}
            </div>
        @endif


      <div class="card mb-4">
          <div class="card-header">
            NewCo. Networks: Sales Module
          </div>
          <div class="card-body">
            <p class="card-text">You are logged in as <strong>{{ Auth::user()->name }}</strong>. Choose an option below.</p>
          </div>
        </div>

      <div class="card-columns">
          @if (Auth::user()->isTeamLeader())
          <div class="card">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title">Users</h5>
              <p class="card-text">Use this screen to view @if (Auth::user()->isTeamLeader()) and create @endif <strong>users</strong>.</p>

              @if (Auth::user()->isTeamLeader())
              <div class="btn-group  d-flex mt-auto">
                    <a href="{{ route('crm.list',['list'=>'users']) }}" class="btn btn-primary w-100"><i class="fas fa-user"></i> View</a>
                    <a href="{{ route('crm.create',['class'=>'user'])}}" class="btn btn-outline-primary w-100"><i class="fas fa-plus"></i> Create</a>
              </div>
              @else
                <a href="{{ route('crm.list',['list'=>'users']) }}" class="btn btn-primary mt-auto"><i class="fas fa-user"></i> View users</a>
              @endif

            </div>
            <div class="card-footer">
                <small class="text-muted">We have <strong>{{ $counts['users'] }}</strong> total users</small>
              </div>
          </div>
          @endif

                @if (Auth::user()->isTeamLeader())
                <div class="card">
                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Teams</h5>
                    <p class="card-text">Use this screen to view and create <strong>teams</strong>.</p>

                    <div class="btn-group  d-flex mt-auto">
                          <a href="{{ route('crm.list',['list'=>'teams']) }}" class="btn btn-primary w-100"><i class="fas fa-users"></i> View</a>
                          <a href="{{ route('crm.edit',['class'=>'team'])}}" class="btn btn-outline-primary w-100"><i class="fas fa-plus"></i> Create</a>
                    </div>

                  </div>
                  <div class="card-footer">
                      <small class="text-muted">We have <strong>{{ $counts['teams'] }}</strong> total teams</small>
                    </div>
                </div>
                @endif


              @if (Auth::user()->isTeamLeader() )
                  <div class="card">
                      <div class="card-body d-flex flex-column">
                          <h5 class="card-title">Catalogue Items</h5>
                          <p class="card-text">Use this screen to view <strong>catalogue items</strong>.</p>
                          <a href="{{ route('crm.catalogue-items',['action'=>'all'])}}" class="btn btn-primary mt-auto"><i class="fas fa-book"></i> View Catalogue Items</a>

                      </div>
                      <div class="card-footer">
                          <small class="text-muted">We have <strong>{{ $counts['catalogue-items'] }}</strong> total catalogue items</small>
                      </div>
                  </div>
              @endif

          <div class="card">
              <div class="card-body d-flex flex-column">
                <h5 class="card-title">Leads</h5>
                <p class="card-text">Use this screen to view <strong>leads</strong>.</p>
                  <div class="btn-group  d-flex mt-auto">
                  <a href="{{ route('crm.list',['list'=>'leads']) }}" class="btn btn-primary w-100"><i class="fas fa-headset"></i> View leads</a>
                      @if (Auth::user()->isTeamLeader() )
                      <a href="{{ route('crm.create',['class'=>'lead']) }}" class="btn btn-outline-primary w-100"><i class="fas fa-plus"></i> Create lead</a>
                      @endif
                  </div>
              </div>
              <div class="card-footer">
                  <small class="text-muted">We have <strong>{{ $counts['leads'] }}</strong> total leads</small>
                </div>
            </div>

            <div class="card">
                <div class="card-body d-flex flex-column">
                  <h5 class="card-title">The open pot</h5>
                  <p class="card-text">Use this screen to view <strong>the open pot</strong>.</p>
                  <a href="{{ route('crm.list',['list'=>'open-pot']) }}" class="btn btn-primary mt-auto"><i class="fas fa-box-open"></i> View the open pot</a>

                </div>
                <div class="card-footer">
                    <small class="text-muted">We have <strong>{{ $counts['open-pot'] }}</strong> leads in the open pot</small>
                  </div>
              </div>

        </div>
  </main>
@endsection

resources/views/crm/themes/basic/screens/datatable.blade.php
@extends('crm.themes.'.config('crm.theme').'.layouts.app')

@section('js')
    {{-- Required for inline editing of dates in Editor --}}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/locale/en-gb.js"></script>

    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

    <script src="//cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.5.1/js/buttons.bootstrap4.min.js"></script>

    <script src="//cdn.datatables.net/select/1.2.5/js/dataTables.select.min.js"></script>

    <script src="{{ asset('vendor/Editor-PHP-1.7.3/js/dataTables.editor.min.js') }}"></script>
    <script src="{{ asset('vendor/Editor-PHP-1.7.3/js/editor.bootstrap4.min.js') }}"></script>

    <link href="{{ asset('css/datatables.css') }}" rel="stylesheet">

    <script>

        var table;
        var editor;

        $(document).ready(function() {

            /**
            * This avoids having to pass the csrf_token to every Ajax call (eg, DataTables Editor)
            **/
            $.ajaxSetup({
                headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
            });

            var columns = {!! json_encode($columns) !!};

            /**
             * Add a render() argument to some columns; it's hard to do this from the
             * PHP Controller, because the function() is wrapped in "" by json_encode
             **/
             $(columns).each(function(index, column) {
                if (column.data == 'full_name') {
                    /**
                     * Allow us to render HTML in this column,
                     * from https://stackoverflow.com/a/12323523/1463965
                     **/
                    /**
                     * TODO: just check for HTML tags here rather than hardcocding the check for column name?
                     **/
                    columns[index]['render'] = function ( data, type, row, meta ) {
                        return $("<div/>").html(data).text();
                    }
                }
                /**
                * TODO: handle teams and roles here to comma separate OR render "None";
                * this will replace the code in CRMController:getColumnsForUsers()
                **/
                else if (column.data == 'teams' || column.data == 'roles') {
                    columns[index]['render'] = function ( data, type, row, meta ) {
                        if (data.length == 0) {
                            return 'None';
                        }
                        else {
                            if (column.data == 'teams') {
                                return $.map(data, function(obj) {return obj.name}).join(',<br>');
                            }
                            else if (column.data == 'roles') {
                                return $.map(data, function(obj) {return obj.title}).join(',<br>');
                            }
                        }

                    }
                }

            });

            columns.push({
                mRender: function (data, type, row) {
                    return '<a class="table-edit btn btn-info btn-sm pull-right" href="'+row.edit_link+'"><i class="far fa-edit"></i> Edit</a>'
                },
                searchable: false,
                orderable: false
            });

            editor = new $.fn.dataTable.Editor( {
                ajax: '{!! route('crm.update',['list'=>$list]) !!}',
                table: '#dataTable',
                fields: {!! json_encode($editable_fields) !!}
            });

            $('#dataTable').on( 'click', 'tbody td.editable', function (e) {
                /**
                * Inline editing:
                editor.inline( this, {
                    buttons: { label: '<i class="fa fa-check"></i>', fn: function () { this.submit(); } }
                } );
                **/

                /**
                * Bubble editing: this works better than inline, IMHO
                **/
                editor.bubble(this);
            } );

            table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('crm.dataTableData',['list'=>$list]) !!}',
                columns: columns,
                /**
                * From https://datatables.net/reference/option/stateSave, means we retain search terms and current page when returning to the table
                **/
                stateSave: true,
                /**
                * Control layout, see https://datatables.net/reference/option/dom
                **/
                /* old version
                dom: "<'row'<'col-sm-4'l><'col-sm-6'f><'col-sm-2'B>>" +
                     "<'row'<'col-sm-12'tr>>" +
                     "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                     */
                     dom: "<'row'<'col-sm-6'l><'col-sm-6'Bf>>" +
                     "<'row'<'col-sm-12'tr>>" +
                     "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                /**
                * Add the "Editor" button for bulk updating
                **/
                @if ($editable_fields)
                buttons: [
                    {
                        extend: "edit",
                        editor: editor,
                        text: "<i class='far fa-edit'></i> Edit",
                        className: 'btn-info btn-sm'
                    },
                ],
                @else
                buttons: [],
                @endif
                /**
                 * Allow rows to be selected, see https://datatables.net/reference/option/select.style
                 */
                select: {
                    style: 'multi+shift',
                },

                /**
                 * Add column filters; see https://datatables.net/examples/api/multi_filter_select.html
                 **/
                initComplete: function () {
                    @foreach ($filters as $column_key=>$filter_values)
                    this.api().columns('{{ $column_key }}').every( function () {

                        var column = this;

                        var header = $(column.header()).text();

                        select_html = '<select><option value="">All '+ header + (header.substr(-1) == 's' ? 'e': '') + 's</option></select>';

                        var select = $(select_html)
                            .appendTo( $(column.header()).empty() )
                            .on( 'change', function () {
                                /**
                                * Removed now that we're using IDs in dropdown filters:
                                *
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                **/
                                var search = $(this).val();
                                if (search) {
                                    search = "^" + search + "$";
                                }
                                column
                                    .search(search, true, false ) // input, regex, smart : see https://datatables.net/reference/api/column().search()
                                    .draw();

                            });
                        var filters = {!! json_encode($filter_values) !!};
                        $.each(filters, function ( id, name ) {
                            /**
                            * If we've filtered by column, and saved state using stateSave,
                            * make sure we pre-select the column option:
                            **/
                            /**
                            * Note that we're switching to using 'id' for a value here;
                            * this makes filtering hasMany values (eg user->roles()) easier
                            * but may require custom filters in the Laravel Datatables query
                            **/
                            /**
                            * The conversion back to a regex here for comparison is a bit clunky
                            **/
                            if (column.search() == '^'+id+'$') {
                                select.append( '<option value="'+id+'" selected="selected">'+name+'</option>' )
                            } else {
                                select.append( '<option value="'+id+'">'+name+'</option>' )
                            }
                        } );
                        select.append( '<option value="0">No '+header+'</option>' );
                    });
                    @endforeach
                }
            });
        } );
    </script>
@endsection

@section('css')
    <link href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet">

    <style>
        /**
        * Not sure why dataTables.bootstrap4.min.css sets border-collapse: separate, it looks odd --}}
        **/
        table.dataTable {
            border-collapse: collapse !important;
        }
        table.dataTable thead th {
            background-color: #fff;
        }
        /**
        * No need to indent the main table wrapper, we do this already via the <main> container:
        **/
        #dataTable_wrapper.container-fluid {
            padding-left: 0;
            padding-right: 0;
        }
        /**
        * Don't put borders on the last (edit) cell:
        **/
        #dataTable th:last-child, #dataTable td:last-child {
            border-left-width: 0;
        }
        #dataTable th:nth-last-child(2), #dataTable td:nth-last-child(2) {
            border-right-width: 0;
        }
        /**
        * Temporary styling of search boxes, buttons:
        **/
        #dataTable_wrapper #dataTable_filter {
            float: right;
        }
        #dataTable_wrapper .dt-buttons {
            margin-left: 1em;
            float: right;
        }

    </style>

    <link href="//cdn.datatables.net/buttons/1.5.1/css/buttons.bootstrap4.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/select/1.2.5/css/select.bootstrap4.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('vendor/Editor-PHP-1.7.3/css/editor.bootstrap4.min.css') }}"/>

@endsection


@section('content')
<main role="main" class="container-fluid">


    <div class="card text-white bg-info mb-2">
        <div class="card-body">
            {{ $page_header }}
        </div>
    </div>
    @forelse ($warnings as $warning)
        <div class="alert alert-warning" role="alert">
            {{ $warning }}
        </div>
    @empty
    {{-- No warnings --}}
    @endforelse

    <table id="dataTable" class="dt-responsive table table-striped table-bordered">
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th>{{ $column->label }}</th>
                @endforeach
                <th>&nbsp;</th>
            </tr>
        </thead>
    </table>
    {{-- Shouldn't need this unless we're working locally, it helps cleared cached table settings while we're changing the number of table columns etc --}}
    @if (App::environment('local'))
    <hr>
    <p><a href="#" onclick="table.state.clear(); window.location.reload();">Clear filter</a></p>
    @endif

</main>
@endsection

resources/views/crm/themes/basic/screens/edit-team.blade.php
@extends('crm.themes.'.config('crm.theme').'.layouts.app')

@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        @if ($team->exists)
                        Edit team
                        @else
                        Create team
                        @endif
                    </div>

                    <div class="card-body border-success">

                            <form _class="form" action="{{ route('crm.update-team',['id'=>$team->id]) }}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Team name</label>
                                    <input class="form-control" type="text" name="name" id="name" value="{{$team->name}}" required>
                                </div>
                                <a href="{{ route('crm.dashboard') }}" class="btn btn-default">Cancel</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>

                    </div>

                </div>
            </div>

        </div>


    </div>

@endsection

resources/views/crm/themes/basic/screens/stripePlans.blade.php
@extends('crm.themes.'.config('crm.theme').'.layouts.app')

@section('content')

    <div class="container">

        <h1></h1>

        <div class="col-sm-12">

            <div class="card">
                <div class="card-header bg-dark text-light">
                    <h3>Plans Available</h3>
                </div>

                <div class="card-body">

                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Plan Identifier <br><small>use this for product association</small></th>
                            <th>Plan Stripe ID</th>
                            <th>Plan Recurring Amount</th>
                            <th>Plan Currency</th>
                            <th>Plan Recurring Point</th>
                            <th>Plan Active</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($stripe_data->data->items as $stripe_datum)
                        <tr>
                            <td>{{$stripe_datum->id}}</td>
                            <td>{{$stripe_datum->stripe_id}}</td>
                            <td>{{$stripe_datum->amount}}</td>
                            <td>{{$stripe_datum->currency}}</td>
                            <td>{{$stripe_datum->interval}}</td>
                            <td>{{$stripe_datum->active}}</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>

            </div>

        </div>

@endsection